export const tableData = [
  {
    postedDate: ' 04/01/2024',
    docDate: '04/30/2024',
    doc: '',
    memo: 'Adjust prepaid insurance balance',
    location: 'Accounts Receivableq',
    jnl: '',
    debit: '9,336.78',
    credit: '0.00',
    balance: '0.00',
  },
  {
    postedDate: '',
    docDate: '',
    doc: '',
    memo: '',
    location: 'Inventory',
    jnl: '',
    debit: '9,336.78',
    credit: '0.00',
    balance: '0.00',
  },
  {
    postedDate: '',
    docDate: '',
    doc: '',
    memo: '',
    location: 'Fixed Assets',
    jnl: '',
    debit: '9,336.78',
    credit: '0.00',
    balance: '0.00',
  },
  {
    postedDate: '',
    docDate: '',
    doc: '',
    memo: '',
    location: 'Accounts Payable',
    jnl: '',
    debit: '9,336.78',
    credit: '0.00',
    balance: '0.00',
  },
  {
    location: 'Loans Payable',
    jnl: '',
    debit: '9,336.78',
    credit: '0.00',
    balance: '0.00',
  },
  {
    location: 'Owner’s Equity',
    jnl: '',
    debit: '9,336.78',
    credit: '0.00',
    balance: '0.00',
  },
  {
    location: 'Revenue',
    jnl: '',
    debit: '9,336.78',
    credit: '0.00',
    balance: '0.00',
  },
  {
    location: 'Expenses',
    jnl: '',
    debit: '9,336.78',
    credit: '0.00',
    balance: '0.00',
  },
];

export const GL_data = [
  {
    date: '2024-01-01',
    account_name: 'Cash',
    journal_entry_description: 'Initial Capital',
    debit: '10000',
    credit: '',
    balance: '10000',
  },
  {
    date: '2024-01-02',
    account_name: 'Office Supplies',
    journal_entry_description: 'Purchase of Office Supplies',
    debit: '500',
    credit: '',
    balance: '9500',
  },
  {
    date: '2024-01-05',
    account_name: 'Account Payable',
    journal_entry_description: 'Payment of Vendor',
    debit: '',
    credit: '2000',
    balance: '7500',
  },
  {
    date: '2024-01-07',
    account_name: 'Sales Revenue',
    journal_entry_description: 'Customer Payment',
    debit: '',
    credit: '3000',
    balance: '10500',
  },
  {
    date: '2024-01-12',
    account_name: 'Cash',
    journal_entry_description: 'Bank Loan Received',
    debit: '5000',
    credit: '',
    balance: '15400',
  },
  {
    date: '2024-01-15',
    account_name: 'Utilities Expense',
    journal_entry_description: 'Payment of Utilies',
    debit: '200',
    credit: '',
    balance: '14300',
  },
  {
    date: '2024-01-20',
    account_name: 'Service Revenue',
    journal_entry_description: 'Income from Service',
    debit: '',
    credit: '4000',
    balance: '18300',
  },
  {
    date: '2024-01-25',
    account_name: 'Salaries Expense',
    journal_entry_description: 'Employee Salaries',
    debit: '3000',
    credit: '',
    balance: '15300',
  },
  {
    date: '2024-01-28',
    account_name: 'Advertising Expense',
    journal_entry_description: 'Online Ad Campaign',
    debit: '700',
    credit: '',
    balance: '14600',
  },
  {
    date: '2024-01-30',
    account_name: 'Interest Expense',
    journal_entry_description: 'Bank Loan Interest',
    debit: '100',
    credit: '',
    balance: '14500',
  },
];
