import { StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  section: {
    width: 640,
    padding: 36,
    backgroundColor: '#ffffff',
    flex: 'column',
    display: 'flex',
    flexDirection: 'column',
    gap: 56,
  },
  heading: {
    color: '#000000',
    fontWeight: 600,
    fontSize: 24,
    fontFamily: 'var(--font-poppins)',
  },
  Text: {
    color: 'var(--gray-600)',
    fontWeight: 400,
    fontSize: 18,
    fontFamily: 'var(--font-poppins)',
  },

  invoice: {
    fontFamily: 'var(--font-poppins)',
    fontWeight: 800,
    fontSize: '36px',
    lineHeight: '54px',
    color: '#000000',
    textTransform: 'uppercase',
  },
  invoiceNumber: {
    fontFamily: 'var(--font-poppins)',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '24px',
    color: 'var(--gray-400)',
  },
  payment: {
    fontFamily: 'var(--font-poppins)',
    fontSize: '18px',
    lineHeight: '27px',
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
    borderRadius: 5,
  },
  tablehead: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: ' hsla(var(--primary))',
    borderRadius: 5,
    color: '#FFFFFF',
    marginBottom: 20,
    paddingLeft: 22,
    paddingRight: 10,
    paddingTop: 13,
    fontWeight: 700,
    alignItems: 'center',
    justifyContent: 'center',
    height: 'auto',
  },
  row: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 10,
    justifyContent: 'space-between',
    width: '100%',
  },
  cell: {
    fontFamily: 'var(--font-poppins)',
    fontSize: '18px',
    lineHeight: '27px',
    width: '25%',
  },
  tablebody: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    color: 'var(--gray-600)',
  },
  flex_end: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 10,
    justifyContent: 'flex-end',
    width: '100%',
  },
  feildPayment: {
    width: '45%',
    display: 'flex',
    justifyContent: 'flex-end',
    color: 'var(--gray-600)',
    fontWeight: 500,
    fontSize: 18,
    fontFamily: 'var(--font-poppins)',
  },
  feildDetail: {
    width: '45%',
    color: '#000000',
    fontWeight: 400,
    fontSize: 18,
    fontFamily: 'var(--font-poppins)',
  },
  contentCenter: {
    display: 'flex',
    justifyContent: 'center',
  },
  color_black: {
    color: '#000000',
  },
});
export default styles;
