"""initial_schema

Revision ID: ca00c8b54ea3
Revises: 
Create Date: 2026-07-26 22:10:55.468892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca00c8b54ea3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE', name='accounttype'), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=True)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('ix_accounts_parent_id'), 'accounts', ['parent_id'], unique=False)
    op.create_index(op.f('ix_accounts_type'), 'accounts', ['type'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('RAW', 'FINISHED', name='itemtype'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('max_stock', sa.Integer(), nullable=False),
    sa.Column('gsm', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('size', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_index(op.f('ix_items_sku'), 'items', ['sku'], unique=True)
    op.create_index(op.f('ix_items_type'), 'items', ['type'], unique=False)
    op.create_table('job_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_number', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('required_date', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('pi_number', sa.String(length=100), nullable=False),
    sa.Column('freight_charges', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='joborderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_orders_customer_name'), 'job_orders', ['customer_name'], unique=False)
    op.create_index(op.f('ix_job_orders_job_number'), 'job_orders', ['job_number'], unique=True)
    op.create_index(op.f('ix_job_orders_status'), 'job_orders', ['status'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('outstanding', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='customerstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_account_id'), 'customers', ['account_id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_table('dispatches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pass_number', sa.String(length=100), nullable=False),
    sa.Column('job_order_id', sa.Integer(), nullable=False),
    sa.Column('job_number', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('dispatch_date', sa.Date(), nullable=False),
    sa.Column('vehicle_no', sa.String(length=100), nullable=False),
    sa.Column('driver', sa.String(length=150), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DISPATCHED', 'CANCELLED', name='dispatchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatches_customer_name'), 'dispatches', ['customer_name'], unique=False)
    op.create_index(op.f('ix_dispatches_job_number'), 'dispatches', ['job_number'], unique=False)
    op.create_index(op.f('ix_dispatches_job_order_id'), 'dispatches', ['job_order_id'], unique=False)
    op.create_index(op.f('ix_dispatches_pass_number'), 'dispatches', ['pass_number'], unique=True)
    op.create_index(op.f('ix_dispatches_status'), 'dispatches', ['status'], unique=False)
    op.create_table('job_consumed_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('consumed_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_consumed_items_item_id'), 'job_consumed_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_job_consumed_items_job_order_id'), 'job_consumed_items', ['job_order_id'], unique=False)
    op.create_table('job_order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('quality', sa.String(length=100), nullable=False),
    sa.Column('colour', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('order_quantity', sa.Integer(), nullable=False),
    sa.Column('order_pending_quantity', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_percent', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_order_lines_item_id'), 'job_order_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_job_order_lines_job_order_id'), 'job_order_lines', ['job_order_id'], unique=False)
    op.create_table('stock_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('transaction_type', sa.Enum('IN', 'OUT', 'ADJUST', name='stocktxntype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transactions_created_at'), 'stock_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_transactions_item_id'), 'stock_transactions', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_transactions_reference_type'), 'stock_transactions', ['reference_type'], unique=False)
    op.create_index(op.f('ix_stock_transactions_transaction_type'), 'stock_transactions', ['transaction_type'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PREFERRED', 'STANDARD', 'UNDER_REVIEW', 'INACTIVE', name='vendorstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_account_id'), 'vendors', ['account_id'], unique=False)
    op.create_index(op.f('ix_vendors_code'), 'vendors', ['code'], unique=True)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_index(op.f('ix_vendors_status'), 'vendors', ['status'], unique=False)
    op.create_table('dispatch_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('job_order_line_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['job_order_line_id'], ['job_order_lines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_lines_dispatch_id'), 'dispatch_lines', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_dispatch_lines_item_id'), 'dispatch_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_dispatch_lines_job_order_line_id'), 'dispatch_lines', ['job_order_line_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=False),
    sa.Column('required_date', sa.Date(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'PARTIAL', 'RECEIVED', 'CANCELLED', name='purchaseorderstatus'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_vendor'), 'purchase_orders', ['vendor'], unique=False)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_number', sa.String(length=100), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('job_order_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'VOID', name='docstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], unique=True)
    op.create_index(op.f('ix_journal_entries_job_order_id'), 'journal_entries', ['job_order_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_purchase_order_id'), 'journal_entries', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_status'), 'journal_entries', ['status'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('gsm', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.Column('po_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_percent', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_item_id'), 'purchase_order_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_purchase_order_id'), 'purchase_order_lines', ['purchase_order_id'], unique=False)
    op.create_table('receivings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receiving_number', sa.String(length=100), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receivings_purchase_order_id'), 'receivings', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_receivings_receiving_number'), 'receivings', ['receiving_number'], unique=True)
    op.create_index(op.f('ix_receivings_vendor'), 'receivings', ['vendor'], unique=False)
    op.create_index(op.f('ix_receivings_vendor_id'), 'receivings', ['vendor_id'], unique=False)
    op.create_table('customer_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_account_id', sa.Integer(), nullable=True),
    sa.Column('job_order_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'VOID', name='docstatus'), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_invoices_customer_account_id'), 'customer_invoices', ['customer_account_id'], unique=False)
    op.create_index(op.f('ix_customer_invoices_customer_id'), 'customer_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_invoices_customer_name'), 'customer_invoices', ['customer_name'], unique=False)
    op.create_index(op.f('ix_customer_invoices_invoice_number'), 'customer_invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_customer_invoices_job_order_id'), 'customer_invoices', ['job_order_id'], unique=False)
    op.create_index(op.f('ix_customer_invoices_purchase_order_id'), 'customer_invoices', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_customer_invoices_status'), 'customer_invoices', ['status'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expense_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('paid_to', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('debit_account_id', sa.Integer(), nullable=False),
    sa.Column('credit_account_id', sa.Integer(), nullable=False),
    sa.Column('job_order_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'VOID', name='docstatus'), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['debit_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_expense_number'), 'expenses', ['expense_number'], unique=True)
    op.create_index(op.f('ix_expenses_job_order_id'), 'expenses', ['job_order_id'], unique=False)
    op.create_index(op.f('ix_expenses_purchase_order_id'), 'expenses', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_expenses_status'), 'expenses', ['status'], unique=False)
    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('debit_account_id', sa.Integer(), nullable=False),
    sa.Column('credit_account_id', sa.Integer(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('job_order_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['credit_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['debit_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_lines_credit_account_id'), 'journal_lines', ['credit_account_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_debit_account_id'), 'journal_lines', ['debit_account_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_job_order_id'), 'journal_lines', ['job_order_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_journal_entry_id'), 'journal_lines', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_purchase_order_id'), 'journal_lines', ['purchase_order_id'], unique=False)
    op.create_table('receiving_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receiving_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiving_id'], ['receivings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receiving_lines_item_id'), 'receiving_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_receiving_lines_purchase_order_line_id'), 'receiving_lines', ['purchase_order_line_id'], unique=False)
    op.create_index(op.f('ix_receiving_lines_receiving_id'), 'receiving_lines', ['receiving_id'], unique=False)
    op.create_table('vendor_bills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_number', sa.String(length=100), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('vendor_account_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('job_order_id', sa.Integer(), nullable=True),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'VOID', name='docstatus'), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_bills_bill_number'), 'vendor_bills', ['bill_number'], unique=True)
    op.create_index(op.f('ix_vendor_bills_job_order_id'), 'vendor_bills', ['job_order_id'], unique=False)
    op.create_index(op.f('ix_vendor_bills_purchase_order_id'), 'vendor_bills', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_vendor_bills_status'), 'vendor_bills', ['status'], unique=False)
    op.create_index(op.f('ix_vendor_bills_vendor_account_id'), 'vendor_bills', ['vendor_account_id'], unique=False)
    op.create_index(op.f('ix_vendor_bills_vendor_id'), 'vendor_bills', ['vendor_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('payment_type', sa.Enum('PAYMENT', 'RECEIPT', name='paymenttype'), nullable=False),
    sa.Column('party_name', sa.String(length=255), nullable=False),
    sa.Column('vendor_bill_id', sa.Integer(), nullable=True),
    sa.Column('customer_invoice_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('job_order_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'VOID', name='docstatus'), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_invoice_id'], ['customer_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_bill_id'], ['vendor_bills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_customer_invoice_id'), 'payments', ['customer_invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_job_order_id'), 'payments', ['job_order_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_type'), 'payments', ['payment_type'], unique=False)
    op.create_index(op.f('ix_payments_purchase_order_id'), 'payments', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_vendor_bill_id'), 'payments', ['vendor_bill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_vendor_bill_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_purchase_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_type'), table_name='payments')
    op.drop_index(op.f('ix_payments_job_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_vendor_bills_vendor_id'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_vendor_account_id'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_status'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_purchase_order_id'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_job_order_id'), table_name='vendor_bills')
    op.drop_index(op.f('ix_vendor_bills_bill_number'), table_name='vendor_bills')
    op.drop_table('vendor_bills')
    op.drop_index(op.f('ix_receiving_lines_receiving_id'), table_name='receiving_lines')
    op.drop_index(op.f('ix_receiving_lines_purchase_order_line_id'), table_name='receiving_lines')
    op.drop_index(op.f('ix_receiving_lines_item_id'), table_name='receiving_lines')
    op.drop_table('receiving_lines')
    op.drop_index(op.f('ix_journal_lines_purchase_order_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_journal_entry_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_job_order_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_debit_account_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_credit_account_id'), table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index(op.f('ix_expenses_status'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_purchase_order_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_job_order_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_number'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_customer_invoices_status'), table_name='customer_invoices')
    op.drop_index(op.f('ix_customer_invoices_purchase_order_id'), table_name='customer_invoices')
    op.drop_index(op.f('ix_customer_invoices_job_order_id'), table_name='customer_invoices')
    op.drop_index(op.f('ix_customer_invoices_invoice_number'), table_name='customer_invoices')
    op.drop_index(op.f('ix_customer_invoices_customer_name'), table_name='customer_invoices')
    op.drop_index(op.f('ix_customer_invoices_customer_id'), table_name='customer_invoices')
    op.drop_index(op.f('ix_customer_invoices_customer_account_id'), table_name='customer_invoices')
    op.drop_table('customer_invoices')
    op.drop_index(op.f('ix_receivings_vendor_id'), table_name='receivings')
    op.drop_index(op.f('ix_receivings_vendor'), table_name='receivings')
    op.drop_index(op.f('ix_receivings_receiving_number'), table_name='receivings')
    op.drop_index(op.f('ix_receivings_purchase_order_id'), table_name='receivings')
    op.drop_table('receivings')
    op.drop_index(op.f('ix_purchase_order_lines_purchase_order_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_item_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_journal_entries_status'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_purchase_order_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_job_order_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_number'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_vendor'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_dispatch_lines_job_order_line_id'), table_name='dispatch_lines')
    op.drop_index(op.f('ix_dispatch_lines_item_id'), table_name='dispatch_lines')
    op.drop_index(op.f('ix_dispatch_lines_dispatch_id'), table_name='dispatch_lines')
    op.drop_table('dispatch_lines')
    op.drop_index(op.f('ix_vendors_status'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_code'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_account_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_stock_transactions_transaction_type'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_reference_type'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_item_id'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_created_at'), table_name='stock_transactions')
    op.drop_table('stock_transactions')
    op.drop_index(op.f('ix_job_order_lines_job_order_id'), table_name='job_order_lines')
    op.drop_index(op.f('ix_job_order_lines_item_id'), table_name='job_order_lines')
    op.drop_table('job_order_lines')
    op.drop_index(op.f('ix_job_consumed_items_job_order_id'), table_name='job_consumed_items')
    op.drop_index(op.f('ix_job_consumed_items_item_id'), table_name='job_consumed_items')
    op.drop_table('job_consumed_items')
    op.drop_index(op.f('ix_dispatches_status'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_pass_number'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_job_order_id'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_job_number'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_customer_name'), table_name='dispatches')
    op.drop_table('dispatches')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_account_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_job_orders_status'), table_name='job_orders')
    op.drop_index(op.f('ix_job_orders_job_number'), table_name='job_orders')
    op.drop_index(op.f('ix_job_orders_customer_name'), table_name='job_orders')
    op.drop_table('job_orders')
    op.drop_index(op.f('ix_items_type'), table_name='items')
    op.drop_index(op.f('ix_items_sku'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_accounts_type'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_parent_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
