import { StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 10,
    fontSize: 10,
    backgroundColor: 'rgba(255, 255, 255, 1)',
  },
  header: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: '30px',
    borderBottom: '1px solid rgba(0, 0, 0, 0.2)',
    backgroundColor: '#FFFFFF',
    width: '90%',
    margin: 'auto',
    fontSize: '13px',
    fontFamily: 'var(--font-Inter)',
    paddingTop: '10px',
    alignItems: 'center',
    flexWrap: 'wrap',
    fontWeight: 700,
    color: 'rgba(0,0,0,1)',
  },
  column: {
    flex: 2,
    textAlign: 'center',
    paddingTop: '10px',
    paddingBottom: '15px',
    borderRight: '1px solid rgba(0, 0, 0, 0.2)',
    backgroundColor: 'white',
    position: 'relative',
    marginRight: '5px',
  },
  wideColumn: {
    flex: 6,
    textAlign: 'center',
    borderRight: '1px solid rgba(0, 0, 0, 0.2)',
    backgroundColor: 'white',
    paddingTop: '10px',
    paddingLeft: '10px',
    paddingBottom: '15px',
    position: 'relative',
    marginRight: '5px',
  },
  row: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    backgroundColor: 'white',
    width: '90%',
    margin: 'auto',
    fontSize: '13px',
    fontFamily: 'var(--font-Inter)',
    fontWeight: 600,
    lineHeight: '30px',
    flex: 2,
  },
  lastColumn: {
    flex: 2,
    textAlign: 'center',
    backgroundColor: 'white',
    paddingTop: '10px',
    paddingBottom: '15px',
  },
  text: {
    lineHeight: '30px',
    fontSize: '13px',
    fontFamily: 'var(--font-Inter)',
  },
  icon: {
    width: 10,
    height: 6,
    marginLeft: 5,
  },
  dropdown: {
    position: 'absolute',
    backgroundColor: '#fff',
    boxShadow: '0px 4px 8px rgba(0,0,0,0.1)',
    padding: '10px',
    zIndex: 1,
  },
});

export default styles;
