import type { Metadata } from 'next';

import { Dashboard } from '@/app/dashboard/_components/layout';
import {
  encodeSans,
  fontInter,
  fontMartelSans,
  fontMontserrat,
  fontPoppins,
} from '@/app/fonts';
import Providers from '@/providers';

export const metadata: Metadata = {
  title: 'FairSplit Sales',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${fontMontserrat.variable} ${fontPoppins.variable} ${fontMartelSans.variable} ${fontInter.variable} ${encodeSans.variable}`}
    >
      <head />
      <body suppressHydrationWarning={true}>
        <Providers>
          <Dashboard>{children}</Dashboard>
        </Providers>
      </body>
    </html>
  );
}
